ServicesUrl:
    ProductsServiceURL: http://Microservices.Monitoring.Products.API/api/products,
    PoliciesServiceURL: http://Microservices.Monitoring.Policy.API/api/policies
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Report.API
    Environment: production
