ServicesUrl:
    ProductsServiceURL: http://Microservices.demo.Product.API/api/products
    PoliciesServiceURL: http://Microservices.demo.Policy.API/api/policies
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Report.API
    Environment: production
