ServicesUrl:
    PricingApiUrl: http://Microservices.Demo.Policy.API/api/policy
    ProductsServiceURL: http://Microservices.Monitoring.Products.API/api/products,
    PoliciesServiceURL: http://Microservices.Monitoring.Policy.API/api/policies
RabbitMQSettings:
    Username: admin
    Password: admin
    Port: 5672
    VirtualHost: /
    Hostnames: 
        - microservices.demo.rabbitmq    
    RequestTimeout: 10
    PublishConfirmTimeout: 1
    RecoveryInterval: 1
    PersistentDeliveryMode: true
    AutoCloseConnection: true
    AutomaticRecovery: true
    TopologyRecovery: true
ElasticApm:
    SecretToken: 
    ServerUrls: http://apm-server:8200
    ServiceName: Microservices.Demo.Report.API
    Environment: production
